services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      SERVICES: dynamodb,s3
      DEBUG: ${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init/ready.d:/etc/localstack/init/ready.d"
      - "./localstack/wait-for-localstack.sh:/home/localstack/wait-for-localstack.sh"
