name: Publish

on:
  workflow_dispatch:
    inputs:
      target_element:
        description: 'Semver element will be incremented'
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm (Ensure npm 11.5.1 or later is installed)
        run: npm install -g npm@latest
      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Bump version
        run: |
          npm version ${{ inputs.target_element }} \
            --include-workspace-root \
            --no-git-tag-version \
            -w packages/bolt-s3 \
            -w packages/bolt-dynamodb
      - name: Get version string
        id: get-version-string
        run: echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
      - run: |
          git add \
            package.json \
            package-lock.json \
            packages/bolt-s3/package.json \
            packages/bolt-dynamodb/package.json
      - run: git commit -m "v${{ steps.get-version-string.outputs.version }}"
      - run: git tag "v${{ steps.get-version-string.outputs.version }}"
      - run: npm ci
      - run: make publish
      - run: git push
      - run: git push origin "v${{ steps.get-version-string.outputs.version }}"

  purge-camo-cache:
    needs: publish
    uses: ./.github/workflows/purge-camo-cache.yaml
