name: Publish

on:
  workflow_dispatch:
    inputs:
      target_element:
        description: 'Semver element will be incremented'
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Bump version
        run: npm version ${{ inputs.target_element }}
      - run: npm ci
      - run: make publish
      - run: git push
      - run: git push --tags
